# Generated by Django 4.1.4 on 2023-10-06 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0002_chathistory_remove_userchats_user_delete_chatwith_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='chatsMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatswith', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chatswith', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
