# Generated by Django 4.1.4 on 2023-10-21 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0003_chatsmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='chathistory',
            name='users',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='chatapp.chatsmenu'),
            preserve_default=False,
        ),
    ]
