# Generated by Django 4.1.4 on 2023-11-11 07:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0004_chathistory_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsmenu',
            name='chatswith',
        ),
        migrations.AddField(
            model_name='chatsmenu',
            name='chatswith',
            field=models.ManyToManyField(related_name='chatswith', to=settings.AUTH_USER_MODEL),
        ),
    ]
