# Generated by Django 4.1.4 on 2023-11-11 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chatapp', '0005_remove_chatsmenu_chatswith_chatsmenu_chatswith'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsmenu',
            name='chatswith',
        ),
        migrations.AlterField(
            model_name='chatsmenu',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chatsmenu',
            name='chatswith',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='chatswith', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
