# Generated by Django 4.1.4 on 2023-12-29 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatapp', '0006_remove_chatsmenu_chatswith_alter_chatsmenu_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatsmenu',
            old_name='user',
            new_name='user1',
        ),
        migrations.RenameField(
            model_name='chatsmenu',
            old_name='chatswith',
            new_name='user2',
        ),
    ]
