# Generated by Django 4.1.4 on 2023-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
