# Generated by Django 4.1.4 on 2023-12-31 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_myuser_date_joined_myuser_first_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='last_name',
        ),
    ]
